version: "2"

formatters:
  enable:
    - gofmt
    - goimports
    - golines

linters:
  enable:
    - depguard
    - govet
    - protogetter
    - staticcheck
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/labset/go-protoc-gen-plugin/
            - google.golang.org/protobuf